var get_Neurons_Url = "/nnod_sql/slq_get_neurons.php?u_id=" + u_id;
var get_Nerves_Url = "/nnod_sql/slq_get_nerves.php?u_id=" + u_id;
var update_Node_Coordinates_Url = "/nnod_sql/slq_update_Node_Coordinates_d.php?u_id=" + u_id;
var delete_Node_Url = "/nnod_sql/slq_delete_neuron_d.php?u_id=" + u_id;
var delete_Edge_Url = "/nnod_sql/slq_delete_edge_d.php?u_id=" + u_id;
var add_Node_Url = "/nnod_sql/slq_add_neuron_d.php?u_id=" + u_id;
var add_Edge_Url = "/nnod_sql/slq_add_nerve_d.php?u_id=" + u_id;
var get_Node_Info_Url = "/nnod_sql/slq_get_neuron_info.php?u_id=" + u_id;
var nnod_node_Url = "nnod_editor_node.php?u_id=" + u_id;
var update_Node_Url = "/nnod_sql/slq_update_Node_d.php?u_id=" + u_id;
var getHTTP_Url = "nnod_editor_getHTTP.php";
var local_triggers_url = "/nnod_sql/slq_get_nn_network.php?u_id=" + u_id;